### ISSUE TITLE
test: API 테스트 추가 

### ISSUE THREAD

**Issue by jongmee** [team-crews/crews-server-spring#28]
## Description ✏️

>버그 발견, 정확한 api 명세 작성을 위해 api 테스트를 전반적으로 보충하고 api 스펙을 점검한다.

## Progress 🐢

- [x] api 테스트 추가
- [x] api 스펙 점검
- [x] api 명세서에 반영
- [x] 테스트 rule 확정

**Comment by jongmee** [comment]
## Todo 📝
- [ ] 지원서 질문 순서 테스트

**Comment by jongmee** [comment]
## 🧪 테스트 rule 확정

- JPQL 쿼리 및 QueryDSL 쿼리 테스트, 서비스 테스트, 컨트롤러(web layer) 테스트는 기존을 유지한다.
- 기존에 `acceptance test`라고 부르던 e2e 시나리오 테스트는 `api test`로 변경한다. `인수 테스트`로 제한하지 않고 e2e 테스트를 진행하고, Rest docs로 문서화한다. 
- api docs를 위한 테스트를 Rest assured를 활용한 e2e 테스트로 진행한 이유는 시간이 없기 때문에 테스트와 api docs 자동화를 한 번에 하기 위해서
